# Project: 职工管理系统
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 职工管理系统.o WorkSpace.o
LINKOBJ  = 职工管理系统.o WorkSpace.o
LIBS     = -L"D:/DEV_CPP/Dev-Cpp/MinGW64/lib" -L"D:/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/DEV_CPP/Dev-Cpp/MinGW64/include" -I"D:/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DEV_CPP/Dev-Cpp/MinGW64/include" -I"D:/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 职工管理系统.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

职工管理系统.o: 职工管理系统.cpp
	$(CPP) -c 职工管理系统.cpp -o 职工管理系统.o $(CXXFLAGS)

WorkSpace.o: WorkSpace.cpp
	$(CPP) -c WorkSpace.cpp -o WorkSpace.o $(CXXFLAGS)
